name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.5.2
        with:
          task_types: '["Build","Chore","CI","Deprecate","Docs","Feat","Fix","Perf","Refactor","Release","Revert","Style","Test"]'
          add_label: 'false'
